context('Testing Autogeneration')

test_that('stub.tests', {

  suppressMessages(create.project('test_project'))

  setwd('test_project')

  suppressMessages(stub.tests())

  expect_that(file.exists(file.path('tests', 'autogenerated.R')), is_true())
  test.code <- scan(file.path('tests', 'autogenerated.R'), what = 'character', sep = '\n')
  expect_that(test.code, equals("expect_that(helper.function(), equals(NULL))"))

  setwd('..')

  unlink('test_project', recursive = TRUE)
})
