stub.tests <- function()
{
  generate.test <- function(fun.name)
  {
    paste('expect_that(', fun.name, '(ARGS), equals(NULL))', sep = '')
  }
  
  unlink(file.path('tests', 'autogenerated.R'))
  
  # Source each file in the `lib` directory in a temporary environment.
  lib.files <- dir('lib')
  tmp.env <- new.env()

  message('Generating stub tests:')
  
  for (lib.file in lib.files)
  {
    sys.source(file.path('lib', lib.file), envir = tmp.env)

    # Create a test for each function created by those files.
    for (symbol in ls(tmp.env))
    {
      if (class(get(symbol, envir = tmp.env)) == 'function')
      {
        cat(generate.test(symbol),
            file = file.path('tests', 'autogenerated.R'),
            append = TRUE)
        cat('\n',
            file = file.path('tests', 'autogenerated.R'),
            append = TRUE)
        message(paste(' ', symbol, sep = ''))
      }
    }
  }
}
